### PR TITLE
Feature/eligibility form

### PR DESCRIPTION
**Pull request by joeywire**

### CODE REVIEW

**Comment by iesous-kurios** [comment]
Looks great, progress bar is cool, I like the moving color bar.  Is there an option to put a number of percent complete as well?

**Comment by joeywire** [comment]
Percentage added to progress bar

**Comment by iesous-kurios** [comment]
Everything looks good for a merge on my end, I will leave some time for Isaiah and/or Chris to check it out as well.

**Review by iesous-kurios — APPROVED** [review]
Looks good, good chunks of info gathering, progress bar is good too.  Considering making the bar take up more space width wise though.

**Pull request merged**
